#!/bin/bash
FLAGS=IOAcc,CommInterface,LLVMInterface,LLVMRuntime,-LLVMParse,Interrupt
# Script to start up full system simulation
build/ARM/gem5.opt --debug-flags=$FLAGS --outdir=BM_ARM_OUT configs/example/fs.py \
--mem-size=4GB --kernel=$M5_PATH/baremetal/VAdd/main.elf --accpath=$M5_PATH/src/hwacc/LLVMRead/Benchmarks \
--disk-image=$M5_PATH/baremetal/common/fake.iso --machine-type=VExpress_GEM5_V1 \
--dtb-file=none --bare-metal --cpu-type=TimingSimpleCPU > BM_ARM_OUT/debug_trace.txt
