#!/bin/bash

if [ "$1" != "" ]; then
    BENCH=$1
else
    echo "No benchmark specified. Using vadd."
    BENCH="vadd"
fi

echo "Performing First Pass: Application = $BENCH"
./baremetalarm $BENCH;

#for (( n=0; n<10; n++)); 
#	do 
#		echo $n
#		./baremetalarm $BENCH; 
#	done


