Import('*')

if env['TARGET_ISA'] == 'arm':

    #
    #SimObject('IOAcc.py')
    SimObject('CommInterface.py')
    SimObject('ComputeUnit.py')
    SimObject('LLVMInterface.py')
    SimObject('ScratchpadMemory.py')
    SimObject('NoncoherentDma.py')
    SimObject('StreamDma.py')
    SimObject('AccCluster.py')
    SimObject('StreamBuffer.py')

    #
    SimObject('HWModeling/SimObjects/CycleCounts.py')
    SimObject('HWModeling/SimObjects/HWInterface.py')

    # 
    Source('comm_interface.cc')
    Source('compute_unit.cc')
    Source('llvm_interface.cc')
    Source('dma_write_fifo.cc')
    Source('noncoherent_dma.cc')
    Source('stream_dma.cc')
    Source('acc_cluster.cc')
    Source('stream_buffer.cc')
    Source('stream_port.cc')
    Source('scratchpad_memory.cc')
    
    #
    Source('LLVMRead/src/value.cc')
    Source('LLVMRead/src/function.cc')
    Source('LLVMRead/src/basic_block.cc')
    Source('LLVMRead/src/debug_flags.cc')
    Source('LLVMRead/src/llvm_types.cc')
    Source('LLVMRead/src/mem_request.cc')
    Source('LLVMRead/src/instruction.cc')
    Source('LLVMRead/src/registers.cc')
    Source('LLVMRead/src/operand.cc')

    #
    Source('HWModeling/src/cycle_counts.cc')
    Source('HWModeling/src/hw_interface.cc')

    #
    DebugFlag('CommInterface')
    DebugFlag('CommInterfaceQueues')
    DebugFlag('DeviceMMR')
    DebugFlag('LLVMInterface')
    DebugFlag('NoncoherentDma')
    DebugFlag('Runtime')
    DebugFlag('RuntimeCompute')
    DebugFlag('RuntimeQueues')
    DebugFlag('SALAM_Debug')
    DebugFlag('StreamBuffer')
    DebugFlag('StreamDma')
    DebugFlag('Trace')
    DebugFlag('Step')

    #
    CompoundFlag('JDEV', ['LLVMInterface', 'Runtime', 'SALAM_Debug'])
    CompoundFlag('HWACC', ['CommInterface', 'LLVMInterface'])