import os
import subprocess

Import('main')

# LLVM 9 install location set with the ENV variable $LLVM_INSTALL
llvm_install = Dir(os.environ['LLVM_INSTALL'])
# Include files for LLVM 9 installation.
llvm_include = llvm_install.Dir('include')
# Library path for LLVM 9 installation.
llvm_libdir = llvm_install.Dir('lib')

llvm_config_path = os.environ['LLVM_INSTALL'] + '/bin/llvm-config'
llvm_libs = subprocess.check_output([llvm_config_path, '--libs'])
llvm_libs = llvm_libs.replace("-l", "")
llvm_libs = llvm_libs.replace("\n", "")
llvm_libs = llvm_libs.split(' ')

main.Append(CPPPATH=[llvm_include])
main.Append(LIBPATH=[llvm_libdir])
# main.Append(LIBS=['LLVM'])
for lib in llvm_libs:
	main.Append(LIBS=[lib])
# -ltinfo needed for llvm
main.Append(LIBS=['tinfo'])