import os
import subprocess

Import('main')

# Use llvm-config to find includes and libraries needed for the build
llvm_include = subprocess.check_output(['llvm-config', '--includedir']).decode()
llvm_include = Dir(llvm_include.replace("\n", ""))
llvm_libdir = subprocess.check_output(['llvm-config', '--libdir']).decode()
llvm_libdir = Dir(llvm_libdir.replace("\n", ""))
llvm_libs = subprocess.check_output(['llvm-config', '--libs']).decode()
llvm_libs = llvm_libs.replace("-l", "")
llvm_libs = llvm_libs.replace("\n", "")
llvm_libs = llvm_libs.split(' ')

main.Append(CPPPATH=[llvm_include])
main.Append(LIBPATH=[llvm_libdir])
# main.Append(LIBS=['LLVM'])
for lib in llvm_libs:
	main.Append(LIBS=[lib])
# -ltinfo needed for llvm
# main.Append(LIBS=['tinfo'])