#!/bin/sh
sudo update-alternatives --install "/usr/bin/clang" "clang" "/usr/bin/clang-12" 100 \
	--slave "/usr/bin/bugpoint"                        "bugpoint"                         "/usr/bin/bugpoint-12" \
	--slave "/usr/bin/clang++"                         "clang++"                          "/usr/bin/clang++-12" \
	--slave "/usr/bin/llc"                             "llc"                              "/usr/bin/llc-12" \
	--slave "/usr/bin/lli"                             "lli"                              "/usr/bin/lli-12" \
	--slave "/usr/bin/llvm-ar"                         "llvm-ar"                          "/usr/bin/llvm-ar-12" \
	--slave "/usr/bin/llvm-as"                         "llvm-as"                          "/usr/bin/llvm-as-12" \
	--slave "/usr/bin/llvm-bcanalyzer"                 "llvm-bcanalyzer"                  "/usr/bin/llvm-bcanalyzer-12" \
	--slave "/usr/bin/llvm-config"                     "llvm-config"                      "/usr/bin/llvm-config-12" \
	--slave "/usr/bin/llvm-cov"                        "llvm-cov"                         "/usr/bin/llvm-cov-12" \
	--slave "/usr/bin/llvm-c-test"                     "llvm-c-test"                      "/usr/bin/llvm-c-test-12" \
	--slave "/usr/bin/llvm-cxxdump"                    "llvm-cxxdump"                     "/usr/bin/llvm-cxxdump-12" \
	--slave "/usr/bin/llvm-diff"                       "llvm-diff"                        "/usr/bin/llvm-diff-12" \
	--slave "/usr/bin/llvm-dis"                        "llvm-dis"                         "/usr/bin/llvm-dis-12" \
	--slave "/usr/bin/llvm-dwarfdump"                  "llvm-dwarfdump"                   "/usr/bin/llvm-dwarfdump-12" \
	--slave "/usr/bin/llvm-dwp"                        "llvm-dwp"                         "/usr/bin/llvm-dwp-12" \
	--slave "/usr/bin/llvm-extract"                    "llvm-extract"                     "/usr/bin/llvm-extract-12" \
	--slave "/usr/bin/llvm-lib"                        "llvm-lib"                         "/usr/bin/llvm-lib-12" \
	--slave "/usr/bin/llvm-link"                       "llvm-link"                        "/usr/bin/llvm-link-12" \
	--slave "/usr/bin/llvm-lto"                        "llvm-lto"                         "/usr/bin/llvm-lto-12" \
	--slave "/usr/bin/llvm-mc"                         "llvm-mc"                          "/usr/bin/llvm-mc-12" \
	--slave "/usr/bin/llvm-nm"                         "llvm-nm"                          "/usr/bin/llvm-nm-12" \
	--slave "/usr/bin/llvm-objdump"                    "llvm-objdump"                     "/usr/bin/llvm-objdump-12" \
	--slave "/usr/bin/llvm-profdata"                   "llvm-profdata"                    "/usr/bin/llvm-profdata-12" \
	--slave "/usr/bin/llvm-ranlib"                     "llvm-ranlib"                      "/usr/bin/llvm-ranlib-12" \
	--slave "/usr/bin/llvm-readobj"                    "llvm-readobj"                     "/usr/bin/llvm-readobj-12" \
	--slave "/usr/bin/llvm-rtdyld"                     "llvm-rtdyld"                      "/usr/bin/llvm-rtdyld-12" \
	--slave "/usr/bin/llvm-size"                       "llvm-size"                        "/usr/bin/llvm-size-12" \
	--slave "/usr/bin/llvm-split"                      "llvm-split"                       "/usr/bin/llvm-split-12" \
	--slave "/usr/bin/llvm-stress"                     "llvm-stress"                      "/usr/bin/llvm-stress-12" \
	--slave "/usr/bin/llvm-symbolizer"                 "llvm-symbolizer"                  "/usr/bin/llvm-symbolizer-12" \
	--slave "/usr/bin/llvm-tblgen"                     "llvm-tblgen"                      "/usr/bin/llvm-tblgen-12" \
	--slave "/usr/bin/obj2yaml"                        "obj2yaml"                         "/usr/bin/obj2yaml-12" \
	--slave "/usr/bin/opt"                             "opt"                              "/usr/bin/opt-12" \
	--slave "/usr/bin/verify-uselistorder"             "verify-uselistorder"              "/usr/bin/verify-uselistorder-12" \
	--slave "/usr/bin/yaml2obj"                        "yaml2obj"                         "/usr/bin/yaml2obj-12"